version: '2'
services:

  front-dev:
    build:
      context: ./client
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"

  server-dev:
    build:
      context: ./server
    depends_on:
      - db-dev
    environment:
      NODE_ENV: development
    ports:
      - "9632:9632"
    volumes:
      - /var/www/html/images:/var/www/html/images
      - ./server:/server
      - /server/node_modules

  db-dev:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo-dev
    ports:
      - "5432:5432"

volumes:
  server-dev:
  front-dev:
