export default {
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_RESPONSE: 'LOGIN_RESPONSE',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_ERROR: 'LOGIN_ERROR',
    REG_ACTION: 'REG_ACTION',
    REG_RESPONSE: 'REG_RESPONSE',
    REG_REQUEST: 'REG_REQUEST',
    REG_ERROR: 'REG_ERROR',
};
